spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hello_servlets
    jpa:
      repositories:
        enabled: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
