spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hello_servlets?useSSL=false&createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create

  data:
    mongodb:
      repositories:
        type: none

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
