PUT http://localhost:8080/hello_servlets_war/books
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "isbn": "21830912830",
  "year": 1995,
  "title": "Design Patterns",
  "authors": [
    "Erich Gamma",
    "Richard Helm",
    "Ralph Johnson",
    "John Vlissides"
  ],
  "link": "https://www.amazon.it/Design-Patterns-Object-Oriented-Addison-Wesley-Professional-ebook/dp/B000SEIBB8"
}

###
